author = {
    'container_type': 'Author', 
 
    'filled': {'indices', 
 'coauthors', 
 'basics', 
 'counts', 
 'publications'},
     'source': <AuthorSource.SEARCH_AUTHOR_SNIPPETS: 2>, 
     'scholar_id': '4bahYMkAAAAJ', 

      'url_picture': 'https://scholar.google.com/citations?view_op=medium_photo&user=4bahYMkAAAAJ', 
 'name': 'Steven A. Cholewiak, PhD', 
 'affiliation': 'Vision Scientist', 
 'email_domain': '@berkeley.edu', 
 'interests': ['Depth Cues', 
 '3D Shape', 
 'Shape from Texture & Shading', 
 'Naive Physics', 
 'Haptics'], 'citedby': 318, 'citedby5y': 240, 'hindex': 9, 'hindex5y': 9, 'i10index': 8, 'i10index5y': 8, 'coauthors': [{'container_type': 'Author', 
 'filled': set(), 'scholar_id': 'ruUKktgAAAAJ', 
 'source': <AuthorSource.CO_AUTHORS_LIST: 3>, 'name': 'Roland Fleming', 
 'affiliation': 'Kurt Koffka Professor of Experimental Psychology, University of Giessen'}, {'container_type': 'Author', 
 'filled': set(), 'scholar_id': 'Smr99uEAAAAJ', 
 'source': <AuthorSource.CO_AUTHORS_LIST: 3>, 'name': 'Martin Banks', 
 'affiliation': 'Professor of Vision Science, UC Berkeley'}, {'container_type': 'Author', 
 'filled': set(), 'scholar_id': '3xJXtlwAAAAJ', 
 'source': <AuthorSource.CO_AUTHORS_LIST: 3>, 'name': 'Gordon D. Love', 
 'affiliation': 'Durham University, Computer Science & Physics'}, {'container_type': 'Author', 
 'filled': set(), 'scholar_id': 'OiVOAHMAAAAJ', 
 'source': <AuthorSource.CO_AUTHORS_LIST: 3>, 'name': 'Hong Z Tan', 
 'affiliation': 'Professor of ECE, Purdue University'}, {'container_type': 'Author', 
 'filled': set(), 'scholar_id': 'MnUboHYAAAAJ', 
 'source': <AuthorSource.CO_AUTHORS_LIST: 3>, 'name': 'Ari Weinstein', 
 'affiliation': 'Deepmind'}, {'container_type': 'Author', 
 'filled': set(), 'scholar_id': 'dqokykoAAAAJ', 
 'source': <AuthorSource.CO_AUTHORS_LIST: 3>, 'name': 'Chia-Chien Wu', 
 'affiliation': "Brigham and Women's Hospital/Harvard Medical School"}, {'container_type': 'Author', 
 'filled': set(), 'scholar_id': 'KoJrMIAAAAAJ', 
 'source': <AuthorSource.CO_AUTHORS_LIST: 3>, 'name': 'Jacob Feldman', 
 'affiliation': 'Professor of Psychology and Cognitive Science, Rutgers University'}, {'container_type': 'Author', 
 'filled': set(), 'scholar_id': 'aYyDsZ0AAAAJ', 
 'source': <AuthorSource.CO_AUTHORS_LIST: 3>, 'name': 'Pratul Srinivasan', 
 'affiliation': 'Research Scientist at Google Research, PhD Student at UC Berkeley'}, {'container_type': 'Author', 
 'filled': set(), 'scholar_id': 'FoVvIK0AAAAJ', 
 'source': <AuthorSource.CO_AUTHORS_LIST: 3>, 'name': 'Peter C. Pantelis', 
 'affiliation': 'Formerly: Indiana University, Rutgers University, University of Pennsylvania'}, {'container_type': 'Author', 
 'filled': set(), 'scholar_id': '6H0mhLUAAAAJ', 
 'source': <AuthorSource.CO_AUTHORS_LIST: 3>, 'name': 'Ren Ng', 
 'affiliation': 'Professor in Computer Science, University of California, Berkeley'}, {'container_type': 'Author', 
 'filled': set(), 'scholar_id': 'rNTIQXYAAAAJ', 
 'source': <AuthorSource.CO_AUTHORS_LIST: 3>, 'name': 'Steven W Zucker', 
 'affiliation': 'Yale University'}, {'container_type': 'Author', 
 'filled': set(), 'scholar_id': 'JPZWLKQAAAAJ', 
 'source': <AuthorSource.CO_AUTHORS_LIST: 3>, 'name': 'Ben Kunsberg', 
 'affiliation': 'Brown University'}, {'container_type': 'Author', 
 'filled': set(), 'scholar_id': '9XRvM88AAAAJ', 
 'source': <AuthorSource.CO_AUTHORS_LIST: 3>, 'name': 'Manish Singh', 
 'affiliation': 'Rutgers University, New Brunswick, NJ'}, {'container_type': 'Author', 
 'filled': set(), 'scholar_id': 'fD3JviYAAAAJ', 
 'source': <AuthorSource.CO_AUTHORS_LIST: 3>, 'name': 'David S. Ebert', 
 'affiliation': 'Silicon Valley Professor of ECE, Purdue University'}, {'container_type': 'Author', 
 'filled': set(), 'scholar_id': 'tD7OGTQAAAAJ', 
 'source': <AuthorSource.CO_AUTHORS_LIST: 3>, 'name': 'Vivek Labhishetty', 
 'affiliation': 'Clinical Director, Neurolens Inc.,'}, {'container_type': 'Author', 
 'filled': set(), 'scholar_id': 'rRJ9wTJMUB8C', 
 'source': <AuthorSource.CO_AUTHORS_LIST: 3>, 'name': 'Joshua B. Tenenbaum', 
 'affiliation': 'MIT'}, {'container_type': 'Author', 
 'filled': set(), 'scholar_id': 'bTdT7hAAAAAJ', 
 'source': <AuthorSource.CO_AUTHORS_LIST: 3>, 'name': 'Chris Baker', 
 'affiliation': 'Chief Scientist, isee AI'}, {'container_type': 'Author', 
 'filled': set(), 'scholar_id': 'KXQb7CAAAAAJ', 
 'source': <AuthorSource.CO_AUTHORS_LIST: 3>, 'name': 'Sung-Ho Kim', 
 'affiliation': 'Professor of Psychology, Ewha Womans University'}, {'container_type': 'Author', 
 'filled': set(), 'scholar_id': 'NN4GKo8AAAAJ', 
 'source': <AuthorSource.CO_AUTHORS_LIST: 3>, 'name': 'Melissa M. Kibbe', 
 'affiliation': 'Assistant Professor, Boston University'}, {'container_type': 'Author', 
 'filled': set(), 'scholar_id': 'nHx9IgYAAAAJ', 
 'source': <AuthorSource.CO_AUTHORS_LIST: 3>, 'name': 'Peter Shirley', 
 'affiliation': 'Nvidia Corporation'}], 'cites_per_year': {2008: 2, 2009: 5, 2010: 7, 2011: 9, 2012: 21, 2013: 15, 2014: 17, 2015: 16, 2016: 38, 2017: 31, 2018: 31, 2019: 61, 2020: 63}, 'publications': [{'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'A frequency-domain analysis of haptic gratings', 
 'pub_year': '2009'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:u5HHmVD_uO8C', 
 'num_citations': 54}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Haptic identification of stiffness and force magnitude', 
 'pub_year': '2008'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:u-x6o8ySG0sC', 
 'num_citations': 51}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'ChromaBlur: Rendering chromatic eye aberration improves accommodation and realism', 
 'pub_year': '2017'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:LI9QrySNdTsC', 
 'num_citations': 32}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Inferring the intentional states of autonomous virtual agents', 
 'pub_year': '2014'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:roLk4NBRz8UC', 
 'num_citations': 30}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Visual perception of the physical stability of asymmetric three-dimensional objects', 
 'pub_year': '2013'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:ufrVoPGSRksC', 
 'num_citations': 30}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Perception of physical stability and center of mass of 3-D objects', 
 'pub_year': '2015'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:hMsQuOkrut0C', 
 'num_citations': 23}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Creating correct blur and its effect on accommodation', 
 'pub_year': '2018'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:kz9GbA2Ns4gC', 
 'num_citations': 20}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Discrimination of real and virtual surfaces with sinusoidal and triangular gratings using the fingertip and stylus', 
 'pub_year': '2012'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:eQOLeE2rZwMC', 
 'num_citations': 11}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Colour, contours, shading and shape: flow interactions reveal anchor neighbourhoods', 
 'pub_year': '2018'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:k8Z6L05lTy4C', 
 'num_citations': 9}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Perception of intentions and mental states in autonomous virtual agents', 
 'pub_year': '2011'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:9yKSN-GCB0IC', 
 'num_citations': 7}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Agency and rationality: Adopting the intentional stance toward evolved virtual agents.', 
 'pub_year': '2016'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:TIZ-Mc8IlK0C', 
 'num_citations': 6}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Intra-and intermanual curvature aftereffect can be obtained via tool-touch', 
 'pub_year': '2013'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:LkGwnXOMwfcC', 
 'num_citations': 6}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': "Contributions of foveal and non-foveal retina to the human eye's focusing response", 'pub_year': '2019'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:i2xiXl-TujoC', 
 'num_citations': 5}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Varifocal virtuality: a novel optical layout for near-eye display', 
 'pub_year': '2017'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:MLfJN-KU85MC', 
 'num_citations': 5}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'The perception of physical stability of 3d objects: The role of parts', 
 'pub_year': '2010'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:zYLM7Y9cAGgC', 
 'num_citations': 5}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Distinguishing between texture and shading flows for 3D shape estimation', 
 'pub_year': '2015'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:KUbvn5osdkgC', 
 'num_citations': 4}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Predicting 3D shape perception from shading and texture flows', 
 'pub_year': '2014'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:EYYDruWGBe4C', 
 'num_citations': 4}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Frequency analysis of the detectability of virtual haptic gratings', 
 'pub_year': '2007'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:d1gkVwhDpl0C', 
 'num_citations': 4}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Towards a unified explanation of shape from shading and texture', 
 'pub_year': '2013'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:_FxGoFyzp5QC', 
 'num_citations': 3}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'ChromaBlur: Rendering Chromatic Eye Aberration Improves Accommodation and Realism in HMDs', 
 'pub_year': '2017'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:tuHXwOkdijsC', 
 'num_citations': 2}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'A perceptual eyebox for near-eye displays', 
 'pub_year': '2020'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:HbR8gkJAVGIC', 
 'num_citations': 1}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Rendering correct blur', 
 'pub_year': '2017'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:lmc2jWPfTJgC', 
 'num_citations': 1}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Appearance controls interpretation of orientation flows for 3D shape estimation', 
 'pub_year': '2015'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:g3aElNc5_aQC', 
 'num_citations': 1}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Limits on the estimation of shape from specular surfaces', 
 'pub_year': '2014'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:L7CI7m0gUJcC', 
 'num_citations': 1}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'The tipping point: Visual estimation of the physical stability of three-dimensional objects', 
 'pub_year': '2013'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:WF5omc3nYNoC', 
 'num_citations': 1}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Perception of Physical Stability of Asymmetrical Three-Dimensional Objects', 
 'pub_year': '2011'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:YsMSGLbcyi4C', 
 'num_citations': 1}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Cutaneous perception', 
 'pub_year': '2010'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:AvfA0Oy_GE0C', 
 'num_citations': 1}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Lags and leads of accommodation: Fact or fiction?', 
 'pub_year': '2020'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:xtoqd-5pKcoC', 
 'num_citations': 0}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Optimal Allocation of Quantized Human Eye Depth Perception for Light Field Display Design', 
 'pub_year': '2020'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:Dip1O2bNi0gC', 
 'num_citations': 0}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Lags and leads of accommodation are smaller than previously thought', 
 'pub_year': '2020'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:PoWvk5oyLR8C', 
 'num_citations': 0}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Creating correct aberrations: why blur isn’t always bad in the eye', 
 'pub_year': '2020'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:SpbeaW3--B0C', 
 'num_citations': 0}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Real-time blur with chromatic aberration drives accommodation and depth perception', 
 'pub_year': '2019'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:S16KYo8Pm5AC', 
 'num_citations': 0}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Peripheral stimulation can override foveal stimulation in driving accommodation', 
 'pub_year': '2019'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:e_rmSamDkqQC', 
 'num_citations': 0}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Pseudo light-field display apparatus', 
 'pub_year': '2019'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:-FonjvnnhkoC', 
 'num_citations': 0}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'ChromaBlur: Rendering natural chromatic aberration drives accommodation effectively', 
 'pub_year': '2018'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:oNZyr7d5Mn4C', 
 'num_citations': 0}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Driving accommodation using simulated higher-order aberrations', 
 'pub_year': '2018'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:M7yex6snE4oC', 
 'num_citations': 0}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Modeling Accommodation Control of the Human Eye: Chromatic Aberration and Color Opponency', 
 'pub_year': '2017'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:b1wdh0AR-JQC', 
 'num_citations': 0}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'The Dark Secrets of Dirty Concavities', 
 'pub_year': '2014'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:ILKRHgRFtOwC', 
 'num_citations': 0}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'What happens to a shiny 3D object in a rotating environment?', 
 'pub_year': '2014'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:vbGhcppDl1QC', 
 'num_citations': 0}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Effects of varied spatial scale on perception of shape from shiny surfaces', 
 'pub_year': '2014'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:4MWp96NkSFoC', 
 'num_citations': 0}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Visually disentangling shading and surface pigmentation when the two are correlated', 
 'pub_year': '2014'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:ML0RJ9NH7IQC', 
 'num_citations': 0}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Perceptual regions of interest for 3D shape derived from shading and texture flows', 
 'pub_year': '2014'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:Z5m8FVwuT1cC', 
 'num_citations': 0}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Visual perception of the physical stability of asymmetric three', 
 'pub_year': '2013'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:kuK5TVdYjLIC', 
 'num_citations': 0}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Visual adaptation to physical stability of objects', 
 'pub_year': '2012'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:W7OEmFMy1HYC', 
 'num_citations': 0}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Curvature aftereffect and visual-haptic interactions in simulated environments', 
 'pub_year': '2011'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:2osOgNQ5qMEC', 
 'num_citations': 0}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'On the edge: Perceived stability and center of mass of 3D objects', 
 'pub_year': '2011'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:Y0pCki6q_DkC', 
 'num_citations': 0}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Perceiving intelligent action: Experiments in the interpretation of intentional motion', 
 'pub_year': '2011'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:IjCSPb-OGe4C', 
 'num_citations': 0}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': '2010 Index IEEE Transactions on Haptics Vol. 3', 
 'pub_year': '2010'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:WZBGuue-350C', 
 'num_citations': 0}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Living within a virtual environment populated by intelligent autonomous agents', 
 'pub_year': '2010'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:UeHWp8X0CEIC', 
 'num_citations': 0}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Pain: Physiological mechanisms', 
 'pub_year': '2010'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:BUYA1_V_uYcC', 
 'num_citations': 0}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Perceptual estimation of variance in orientation and its dependence on sample size', 
 'pub_year': '2009'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:BwyfMAYsbu0C', 
 'num_citations': 0}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'Haptic stiffness identification and information transfer', 
 'pub_year': '2007'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:p__nRnzSRKYC', 
 'num_citations': 0}, {'container_type': 'Publication', 
 'source': <PublicationSource.AUTHOR_PUBLICATION_ENTRY: 2>, 'bib': {'title': 'This manuscript has been accepted for publication at Decision'}, 'filled': False, 'author_pub_id': '4bahYMkAAAAJ:tYavs44e6CUC', 
 'num_citations': 0}]}